spring:
  application:
    name: eureka
    
server:
  port: 8080

#eureka:
#  instance:
#    hostname: localhost

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8080/eureka/
#    register-with-eureka: false
#    fetch-registry: false

#spring.redis.host=localhost
#spring.redis.port=6379
