spring:
  application:
    name: gateway
    
server:
  port: 8087
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/

zuul:
  proxy:
      addProxyHeaders: true 
  routes:
    rest-clients:
      url: http://localhost:9080
      sensitive-headers:

ribbon:
  eureka:
    enabled: false
