spring:
  application:
    name: gateway
    
server:
  port: 8082
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/

zuul:
  routes:
    clients:
      url: http://localhost:9080
      path: /**
      sensitive-headers: Set-Cookie,Authorization
 #   products:
 #     url: http://localhost:9081
 #     path: /**
 #     sensitive-headers: Set-Cookie,Authorization

ribbon:
  eureka:
    enabled: false
