spring:
  application:
    name: gateway
    
server:
  port: 8082
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/

zuul:
  proxy:
      addProxyHeaders: true 
  routes:
    account-service:
      sensitive-headers: Set-Cookie,Authorization
    customer-service:
      sensitive-headers: Set-Cookie,Authorization
    registration-users:
      sensitive-headers: Set-Cookie,Authorization
    clients-registration:
      sensitive-headers: Set-Cookie,Authorization

ribbon:
  eureka:
    enabled: true
