spring:
  application:
    name: gateway
    
server:
  port: 8082
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/

zuul:
  routes:
    clients:
      url: http://localhost:8082
      path: /**
      sensitive-headers: Set-Cookie,Authorization

ribbon:
  eureka:
    enabled: false
