server:  
  port: 8088

spring:  
  application:
    name: registration-users
  datasource:
    url: jdbc:mysql://localhost/oauth2
    username: oauth2
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        hbm2ddl:
          auto: validate
          
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/ 

security:
  user:
    password: none
  oauth2:
    client:
      client-id: account-service
      client-secret: secret
      #scope: read
      access-token-uri: http://localhost:8000/oauth/token
      user-authorization-uri: http://localhost:8000/oauth/authorize
    resource:
      token-info-uri: http://localhost:8000/oauth/check_token

endpoints:
  security:
    get:
      all: "hasRole('ROLE_PUMA_ADMIN') or hasRole('ROLE_TEST')"
