spring:
  application:
    name: rest-clients

server:
  port: 9080
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
      
security:
  basic:
    enabled: false
  oauth2:
    resource:
      userInfoUri: http://localhost:8000/user

custom-var:
  roles: ROLE_ADMIN
