server:  
  port: ${PORT:9411}

spring:  
  application:
    name: zipkin-service
 
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/ 

    
logging:
  level:
    org.springframework.security: DEBUG
