spring:
  cloud:
    config:
      name: zipkin-service
      discovery:
        service-id: config
        enabled: true

server:
  port: 9411

eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5

logging:
  level:
    org:
      springframework:
        web: debug
